version: '3.8'

services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  auth:
    build:
      context: ./auth-server
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production

  kids:
    build:
      context: ./kids-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "85:85"
    depends_on:
      - auth
      - kids

volumes:
  mongo-data: